# -*- coding: utf-8 -*-
"""TechChallenge 4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15DHC4dtYixuwlrjp68I6Ev7JwF_-CFYJ

#**Importações, abertura e reconhecimento dos dados**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import MinMaxScaler

df = pd.read_csv('/content/Obesity.csv')

df.info()

display(df.head())
display(df.tail())

df['Age'] = df['Age'].astype(int)
df.tail()

df['FAF'] = df['FAF'].astype(int)
df.tail()

df['TUE'] = df['TUE'].astype(int)
df.tail()

df['FCVC'] = df['FCVC'].astype(int)
df.tail()

df['NCP'] = df['NCP'].astype(int)
df.tail()

"""#**Tratamento e normalização dos dados**"""

norma_Gender = {'Female':1, 'Male':0}
df['N_Gender'] = df['Gender'].map(norma_Gender)

df['N_Age'] = df['Age']

df['N_Height'] = df['Height']

df['N_Weight'] = df['Weight']

norma_family_history = {'no':0, 'yes':1}
df['N_family_history'] = df['family_history'].map(norma_family_history)

norma_FAVC = {'no':0, 'yes':1}
df['N_FAVC'] = df['FAVC'].map(norma_family_history)

df['N_FCVC'] = df['FCVC']

df['N_NCP'] = df['NCP']

norma_CAEC = {'no':0, 'Sometimes':1, 'Frequently':2, 'Always':3}
df['N_CAEC'] = df['CAEC'].map(norma_CAEC)

norma_SMOKE = {'no':0, 'yes':1}
df['N_SMOKE'] = df['SMOKE'].map(norma_SMOKE)

df['N_CH2O'] = df['CH2O']

norma_SCC = {'no':0, 'yes':1}
df['N_SCC'] = df['SCC'].map(norma_SCC)

df['N_FAF'] = df['FAF']

df['N_TUE'] = df['TUE']

norma_CALC = {'no':0, 'Sometimes':1, 'Frequently':2, 'Always':3}
df['N_CALC'] = df['CALC'].map(norma_CALC)

norma_MTRANS = {'Public_Transportation':2, 'Walking':0, 'Automobile':4, 'Motorbike':3, 'Bike':1}
df['N_MTRANS'] = df['MTRANS'].map(norma_MTRANS)

norma_Obesity = {'Insufficient_Weight':0, 'Normal_Weight':1, 'Overweight_Level_I':2, 'Overweight_Level_II':3, 'Obesity_Type_I':4, 'Obesity_Type_II':5, 'Obesity_Type_III':6}
df['N_Obesity'] = df['Obesity'].map(norma_Obesity)

display(df.head())
display(df.tail())

numericos = df.select_dtypes(include=np.number).columns.tolist()
print("Numeric columns:", numericos)

df.info()

from sklearn.preprocessing import MinMaxScaler

numerical_n_cols = [col for col in df.select_dtypes(include=np.number).columns if col.startswith('N_')]
scaler = MinMaxScaler()
df[numerical_n_cols] = scaler.fit_transform(df[numerical_n_cols])

display(df.head())
display(df.tail())

for col in numericos:

    df[col] = df[col].apply(lambda x: f"{x:.2f}")
    df[col] = df[col].astype(str).str.replace('.', ',', regex=False)

display(df.head())
display(df.tail())

"""#**Preparação para exportação**"""

df = df.reindex(columns=['Gender','N_Gender','Age','N_Age','Height','N_Height','Weight','N_Weight','family_history','N_family_history',
                    'FAVC','N_FAVC','FCVC','N_FCVC','NCP','N_NCP','CAEC','N_CAEC','SMOKE','N_SMOKE','CH2O','N_CH2O','SCC','N_SCC',
                    'FAF','N_FAF','TUE','N_TUE','CALC','N_CALC','MTRANS','N_MTRANS','Obesity','N_Obesity'])

df.to_csv('Obesity_normalizado.csv', index=False)

