# -*- coding: utf-8 -*-
"""Tech_Challenge_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G1in5TGaI9FqnsCd_iaSPPLce0N5ptRo
"""

import pandas as pd

df = pd.read_csv('/content/Dados Históricos - Ibovespa 02-01-2020_a_30-05-2025.csv', delimiter=',')

df['Data'] = pd.to_datetime(df['Data'], format='%d.%m.%Y')
df = df.sort_values('Data')
df.head()

df.dropna()

df['Vol.'] = df['Vol.'].str.replace('.', '')
df['Vol.'] = df['Vol.'].str.replace(',', '.')

def converter_volume (valor):
  if isinstance(valor, str):
    if 'M' in valor:
      return float(valor.replace('M', '')) * 1_000_000
    elif 'B' in valor:
      return float(valor.replace('B', '')) * 1_000_000_000
  return valor

df['Vol.'] = df['Vol.'].apply(converter_volume)
df['Vol.'] = pd.to_numeric(df['Vol.'])

df.head()

df.tail()

df['Vol.'] = df['Vol.'].astype(int)
df.tail()

df.rename(columns={'Var%': 'Var Percent'}, inplace=True)

df['Var Percent'] = df['Var Percent'].str.replace('%', '')
df['Var Percent'] = df['Var Percent'].str.replace(',', '.')
df['Var Percent'] = df['Var Percent'].astype(float).round(4)
df.head()

#df['Var%'] = df['Var%'].astype(float)*0.01
#df.head()

df['Variacao 1/0'] = (df['Último'].shift(-1) > df['Último']).astype(int)
df['Variacao 1/0'] = df['Variacao 1/0'].shift(1).fillna(1).astype(int)
df.head(20)

df['mm_5'] = df['Último'].rolling(window=5).mean().fillna(0).astype(float).round(4)
df['mm_10'] = df['Último'].rolling(window=10).mean().fillna(0).astype(float).round(4)
df.head(20)

df['retorno_diario'] = df['Último'].pct_change().fillna(0).astype(float).round(4)
df.head(20)

df['retorno_acumulado'] = (df['Último'] / df['Último'].iloc[0]) - 1
df['retorno_acumulado'] = df['retorno_acumulado'].fillna(0).round(4)
df.head()

df['volatilidade_5d'] = df['retorno_diario'].rolling(window=5).std().fillna(0).round(4)
df['vol_21d'] = df['retorno_diario'].rolling(window=21).std().fillna(0).round(4)
df['vol_historica_anual'] = round(df['vol_21d'] * (252**0.5), 4)
df['vol_historica'] = round(df['retorno_diario'].std(), 4)
df.head(22)

correlacao = df['Último'].corr(df['Vol.'])
df['correlacao_fechamento_volume'] = correlacao
df['correlacao_fechamento_volume'] = df['correlacao_fechamento_volume'].round(4)
df.head()

df = df.fillna(0)
df.head()

df.dtypes

df.to_csv('Ibovespa 02-01-2020_a_30-05-2025_ajustado.csv', index=False)

df.to_excel('Ibovespa 02-01-2020_a_30-05-2025_ajustado.xlsx', index=False)

"""# Dataset 2"""

df_2 = pd.read_csv('/content/Dados Históricos - Ibovespa 02-01-2020_a_01-07-2025.csv', delimiter=',')

df_2['Data'] = pd.to_datetime(df_2['Data'], format='%d.%m.%Y')
df_2= df_2.sort_values('Data')
df_2.tail()

df_2.dropna()

df_2['Vol.'] = df_2['Vol.'].str.replace('.', '')
df_2['Vol.'] = df_2['Vol.'].str.replace(',', '.')

df_2['Vol.'] = df_2['Vol.'].apply(converter_volume)
df_2['Vol.'] = pd.to_numeric(df_2['Vol.'])

df_2['Vol.'] = df_2['Vol.'].astype(int)
df_2.tail()

df_2.rename(columns={'Var%': 'Var Percent'}, inplace=True)

df_2['Var Percent'] = df_2['Var Percent'].str.replace('%', '')
df_2['Var Percent'] = df_2['Var Percent'].str.replace(',', '.')
df_2['Var Percent'] = df_2['Var Percent'].astype(float).round(4)
df_2.head()

df_2['Variacao 1/0'] = (df_2['Último'].shift(-1) > df_2['Último']).astype(int)
df_2['Variacao 1/0'] = df_2['Variacao 1/0'].shift(1).fillna(1).astype(int)
df_2.head(20)

df_2['mm_5'] = df_2['Último'].rolling(window=5).mean().fillna(0).astype(float).round(4)
df_2['mm_10'] = df_2['Último'].rolling(window=10).mean().fillna(0).astype(float).round(4)
df_2.tail()

df_2['retorno_diario'] = df_2['Último'].pct_change().fillna(0).astype(float).round(4)
df_2.head(20)

df_2['retorno_acumulado'] = (df_2['Último'] / df_2['Último'].iloc[0]) - 1
df_2['retorno_acumulado'] = df_2['retorno_acumulado'].fillna(0).round(4)
df_2.head()

df_2['volatilidade_5d'] = df_2['retorno_diario'].rolling(window=5).std().fillna(0).round(4)
df_2['vol_21d'] = df_2['retorno_diario'].rolling(window=21).std().fillna(0).round(4)
df_2['vol_historica_anual'] = round(df_2['vol_21d'] * (252**0.5), 4)
df_2['vol_historica'] = round(df_2['retorno_diario'].std(), 4)
df_2.head(22)

correlacao = df_2['Último'].corr(df_2['Vol.'])
df_2['correlacao_fechamento_volume'] = correlacao
df_2['correlacao_fechamento_volume'] = df_2['correlacao_fechamento_volume'].round(4)
df_2.head()

df_2 = df_2.fillna(0)
df_2.head()

df_2.dtypes

df_2.to_csv('Ibovespa 02-01-2020_a_01-07-2025_ajustado.csv', index=False)

df_2.to_excel('Ibovespa 02-01-2020_a_01-07-2025_ajustado.xlsx', index=False)

