# -*- coding: utf-8 -*-
"""Datathon_correto.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ke0n30k5a2qX2enKyXxANQNjRdlh7WdK
"""

import pandas as pd
from sklearn.impute import KNNImputer
from sklearn.preprocessing import MinMaxScaler
import numpy as np
import sqlite3

# Lista dos caminhos dos arquivos Excel
file_paths = [
    "/content/PEDE_2022.xlsx",
    "/content/PEDE_2023.xlsx",
    "/content/PEDE_2024.xlsx"
]

dfs = []


for file in file_paths:
    print(f"Lendo o arquivo: {file}")
    df = pd.read_excel(file)
    dfs.append(df)


combined_df = pd.concat(dfs, ignore_index=True)

print("\n--- Visualização do DataFrame combinado ---")

print("Primeiras 5 linhas do DataFrame combinado:")
print(combined_df.head())

print("\nInformações gerais do DataFrame combinado:")
combined_df.info()

print(f"\nO DataFrame combinado possui {combined_df.shape[0]} linhas e {combined_df.shape[1]} colunas.")

all_numeric_candidates = combined_df.select_dtypes(include=np.number).columns.tolist()
if 'Ano' in all_numeric_candidates:
    all_numeric_candidates.remove('Ano')


df_cols_to_impute = combined_df[all_numeric_candidates].copy()


cols_to_drop_impute = df_cols_to_impute.columns[df_cols_to_impute.isnull().all()].tolist()
if cols_to_drop_impute:
    print(f"Dropping the following all-NaN numeric columns before imputation: {cols_to_drop_impute}")
    df_cols_to_impute = df_cols_to_impute.drop(columns=cols_to_drop_impute)


imputation_target_cols = df_cols_to_impute.columns.tolist()


cols_to_keep_as_is = [col for col in combined_df.columns if col not in imputation_target_cols]
df_cols_to_keep_as_is = combined_df[cols_to_keep_as_is]


imputer = KNNImputer(n_neighbors=5)


df_imputed_numeric = pd.DataFrame(imputer.fit_transform(df_cols_to_impute),
                                  columns=imputation_target_cols,
                                  index=df_cols_to_impute.index)


combined_df_imputed = pd.concat([df_cols_to_keep_as_is, df_imputed_numeric], axis=1)

print("DataFrame após imputação com KNNImputer (apenas colunas numéricas válidas, exceto 'Ano'):")
print(combined_df_imputed.head())
print("\nInformações gerais do DataFrame imputado:")
combined_df_imputed.info()

float_cols = combined_df_imputed.select_dtypes(include=['float64']).columns

# Aplicar formatação para duas casas decimais apenas às colunas float
for col in float_cols:
    combined_df_imputed[col] = combined_df_imputed[col].round(2)

combined_df_imputed.to_excel('combined_df_imputed.xlsx', index=False)

selected_columns = [
    'RA',
    'Idade',
    'Gênero', # Será renomeada para 'Sexo'
    'Instituição de ensino', # Será renoeamda para 'IE'
    'INDE 2022',
    'INDE 2023',
    'INDE 2024',
    'Fase',
    'Turma',
    'Cg',
    'Cf',
    'Ct',
    'Rec Av1',
    'Rec Av2',
    'Rec Av3',
    'Rec Av4',
    'IAA',
    'IEG',
    'IPS',
    'IDA',
    'Mat',
    'Por',
    'Atingiu PV',
    'IPV',
    'IAN',
    'Defasagem',
    'Destaque IEG',
    'Destaque IDA',
    'Destaque IPV',
    'IPP'
]


existing_selected_columns = [col for col in selected_columns if col in combined_df_imputed.columns]
df_final = combined_df_imputed[existing_selected_columns].copy()

# --- Ajustes das colunas ---


rename_mapping = {'Instituição de ensino': 'IE', 'Gênero': 'Sexo'}
df_final = df_final.rename(columns={k: v for k, v in rename_mapping.items() if k in df_final.columns})


if 'Idade' in df_final.columns:
    df_final['Idade'] = pd.to_numeric(df_final['Idade'], errors='coerce')


if 'INDE 2024' in df_final.columns:
    df_final['INDE 2024'] = pd.to_numeric(df_final['INDE 2024'], errors='coerce')


def map_rec_av(value):
    if pd.isna(value):
        return np.nan
    elif 'Mantido na Fase' in str(value):
        return 0
    elif 'Promovido de Fase' in str(value):
        return 1
    else:
        return np.nan

rec_av_cols = ['Rec Av1', 'Rec Av2', 'Rec Av3', 'Rec Av4']
for col in rec_av_cols:
    if col in df_final.columns:
        df_final[col] = df_final[col].apply(map_rec_av)

# Display head and info of the new DataFrame
print("--- Novo DataFrame 'df_final' ---")
print(df_final.head())
print("\nInformações gerais do novo DataFrame:")
df_final.info()

df_final.to_excel('df_final.xlsx', index=False)
print('DataFrame salvo como df_final.xlsx')

df_final = pd.read_excel('df_final.xlsx')

numeric_cols_for_normalization = df_final.select_dtypes(include=['float64', 'int64']).columns.tolist()

scaler = MinMaxScaler()


df_normalized = df_final.copy()

normalized_data = pd.DataFrame(index=df_final.index)


for col in numeric_cols_for_normalization:
    if col in df_final.columns:

        normalized_data[f'N_{col}'] = scaler.fit_transform(df_final[[col]])



PEDE_Completo_Normalizado = pd.concat([df_final, normalized_data], axis=1)



PEDE_Completo_Normalizado['Sexo'] = PEDE_Completo_Normalizado['Sexo'].replace({
    'Menina': 'Feminino',
    'Menino': 'Masculino'
})

PEDE_Completo_Normalizado['N_Sexo'] = PEDE_Completo_Normalizado['Sexo'].astype('category').cat.codes.astype(float)


def map_atingiu_pv(value):
    if pd.isna(value):
        return np.nan
    elif 'Não' in str(value):
        return 0.0
    elif 'Sim' in str(value):
        return 1.0
    else:
        return np.nan

PEDE_Completo_Normalizado['N_Atingiu PV'] = PEDE_Completo_Normalizado['Atingiu PV'].apply(map_atingiu_pv)



float_cols = PEDE_Completo_Normalizado.select_dtypes(include=['float64']).columns

for col in float_cols:
    PEDE_Completo_Normalizado[col] = PEDE_Completo_Normalizado[col].round(2)



PEDE_Completo_Normalizado.to_excel('PEDE_Completo_Normalizado.xlsx', index=False)
print('DataFrame salvo como PEDE_Completo_Normalizado.xlsx')

# Define o nome do arquivo do banco de dados SQLite
db_file = 'PEDE_database.db'

# Define o nome da tabela no banco de dados
table_name = 'PEDE_Normalizado'

# Cria uma conexão com o banco de dados SQLite (se não existir, ele será criado)
conn = sqlite3.connect(db_file)

PEDE_Completo_Normalizado.to_sql(table_name, conn, if_exists='replace', index=False)

conn.close()

print(f"DataFrame '{table_name}' salvo com sucesso no banco de dados SQLite: {db_file}")

