# -*- coding: utf-8 -*-
"""Micro_dados_tech3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qcieyyTFWRNwCYRWRXjLIZlBzhHdBju2
"""

import pandas as pd

df= pd.read_csv('/content/PNAD_COVID_092020.csv', delimiter= ",", engine= 'python')
df2= pd.read_csv('/content/PNAD_COVID_102020.csv', delimiter= ",", engine= 'python')
df3= pd.read_csv('/content/PNAD_COVID_112020.csv', delimiter= ",", engine= 'python')
dicionario = pd.read_excel('/content/Dicionario_PNAD.xlsx')

df_combinado = pd.concat([df, df2, df3], ignore_index=True)
df_combinado.head()

df_combinado.info()

for col in df_combinado.columns:
    if df_combinado[col].dtype == 'object':
        try:

            df_combinado[col] = pd.to_numeric(df_combinado[col], errors='coerce')

            df_combinado[col] = df_combinado[col].apply(lambda x: str(int(x)) if pd.notna(x) and x.is_integer() else x)
        except ValueError:

            pass

display(df_combinado.head())

df_combinado = df_combinado.fillna('')
df_combinado.head()

df_combinado.to_csv('PNAD_COVID_Completo.csv', index=False)

import sqlite3

# Cria um banco de dados e conecta a ele
conn = sqlite3.connect('pnad_covid.db')

# Popula o banco de dados com o arquivo desejado
df_combinado.to_sql('pnad_data', conn, index=False, if_exists='replace')

# Fechar banco
conn.close()

